import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import "@/styles/App.css"
import "@/styles/index.css"

import { AnimatedThemeToggler } from "@/components/magicui/animated-theme-toggler";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/context/auth-context";
import PopUpPreview from "./PopUpPreview";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ThemeProvider>
            {/* Dreamy Sky Pink Glow */}
            {/* <div
            className="absolute inset-0 z-0"
            style={{
              backgroundImage: `
              radial-gradient(circle at 30% 70%, rgba(173, 216, 230, 0.35), transparent 90%),
              radial-gradient(circle at 70% 30%, rgba(255, 182, 193, 0.4), transparent 60%)`,
              }}
              /> */}
            {/* Your Content/Components */}
            <Toaster />
            {children}
            {/* persistent floating chat widget */}
            <PopUpPreview />
            <Script
              id="midtrans-snap"
              src={process.env.NEXT_PUBLIC_MIDTRANS_SNAP_URL!}
              data-client-key={process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
              strategy="afterInteractive"
            />

            <AnimatedThemeToggler className="fixed bottom-6 right-6" />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
